### ISSUE TITLE
Catch StatusCodeException

### ISSUE THREAD

**Issue by kmein** [factisresearch/influx#1]
Please catch the exception if the client program fails to connect to the database.

**Comment by timjb** [comment]
What should the library do when it catches the exception?

**Comment by kmein** [comment]
Quit trying to connect and say that Something Bad™ happened, in fact it can do anything as long as it doesn't let the client code crash

**Comment by sternenseemann** [comment]
I guess a good idea is to have an `Either`-Type to let programs deal with errors conveniently.

**Comment by kmein** [comment]
Well, _either_ that, or a more high-level approach with `Control.Monad.Except` which is AFAIK just a wrapper around a value that can fail with a string error message.

**Comment by sternenseemann** [comment]
_Except_ we don't even need to use such an approach since the error codes are well-defined. We'll use a sum type that can represent all errors and success as well.

**Comment by kmein** [comment]
So, did you already _type_ the sum-type in?

**Comment by sternenseemann** [comment]
@timjb almost got all cases _summed_ up by now!

**Comment by kmein** [comment]
But there may be _sum_thing that keeps him from _summing_ them all up, right?

**Comment by timjb** [comment]
Here's a preview:

``` haskell
data QueryFailureReason
    = BadInfluxQueryRequest Text -- ^ Unacceptable request. Can occur with a syntactically incorrect query. The returned JSON offers further information.
    | QueryFailureHttpException HttpException -- ^ any other 'HTTPException'
    deriving (Show)

data QueryResponse a
    = QueryResult a
    | QueryFailed QueryFailureReason
    deriving (Show)

data WriteFailureReason
    = BadInfluxWriteRequest Text -- ^ Unacceptable request (status code 400). Can occur with a Line Protocol syntax error or if a user attempts to write values to a field that previously accepted a different value type. The returned JSON offers further information.
    | InfluxDbDoesNotExist Text -- ^ Unacceptable request (status code 404). Can occur if a user attempts to write to a database that does not exist. The returned JSON offers further information.
    | InfluxServerError Text -- ^ The system is overloaded or significantly impaired. Can occur if a user attempts to write to a retention policy that does not exist. The returned JSON offers further information.
    | WriteFailureHttpException HttpException -- ^ any other 'HTTPException'
    deriving (Show)

data WriteResponse
    = WriteSuccessful
    | WriteFailed WriteFailureReason
    deriving (Show)
```

The comments are copied from the [InfluxDB API documentation](https://docs.influxdata.com/influxdb/v0.13/concepts/api/).

**Comment by kmein** [comment]
That's _sum_ nice code right there!

**Comment by sternenseemann** [comment]
Your jokes are becoming _unacceptable_ and _overloading_.

**Comment by kmein** [comment]
``` haskell
{-# LANGUAGE OverloadedJokes #-}
```

**Comment by sternenseemann** [comment]
I can't seem to compile the following code:

``` haskell
kmeinJokes :: [GoodJokes]
kmeinJokes = ["That's sum nice code right there!", "But there may be sumthing that keeps him from summing them all up, right?"]
```

Is this a bug in the language extension or correct behavior?

**Comment by kmein** [comment]
You mis_typed_ there. The type "list of good jokes" has to be `[GoodJoke]` -- I guess that's why.

**Comment by sternenseemann** [comment]
Good Point but it still does not compile! Is there anything like `ExcellentJoke`?

**Comment by kmein** [comment]
That's quite a philosophical question...
